"""Add is_public column to the schemas

Revision ID: 1712570344bd
Revises: ccc92a45394a
Create Date: 2025-08-08 15:31:08.145579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1712570344bd'
down_revision = 'ccc92a45394a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('degree', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('experience', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('skill', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('skill_sources', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_sources', 'is_public')
    op.drop_column('skill', 'is_public')
    op.drop_column('experience', 'is_public')
    op.drop_column('degree', 'is_public')
    op.drop_column('certificate', 'is_public')
    # ### end Alembic commands ###
