"""Refactor Question model to use Answer table

Revision ID: 3ace561c4ca0
Revises: 678be95dcd32
Create Date: 2025-10-17 12:09:17.955988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ace561c4ca0'
down_revision = '678be95dcd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('char_limit', sa.Integer(), nullable=True))
    op.drop_column('questions', 'details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('questions', 'char_limit')
    # ### end Alembic commands ###
