"""Add is_archived to JobApplication

Revision ID: 3ebc9e579235
Revises: b7ce7321b735
Create Date: 2025-09-11 16:05:37.872595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebc9e579235'
down_revision = 'b7ce7321b735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_application', 'is_archived')
    # ### end Alembic commands ###
