"""Edit questions table

Revision ID: 4320443fdd6e
Revises: fd5d3c9ddc0e
Create Date: 2025-12-08 13:39:11.038670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4320443fdd6e'
down_revision = 'fd5d3c9ddc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.Text(), nullable=True))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.alter_column('tests', 'test_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'test_type',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###
