"""Recreated the Responsibilities and Achievements

Revision ID: 678be95dcd32
Revises: 8ddd7f864340
Create Date: 2025-10-16 16:11:44.636875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678be95dcd32'
down_revision = '8ddd7f864340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('experience', sa.Column('achievements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'achievements')
    op.drop_column('experience', 'responsibilities')
    # ### end Alembic commands ###
