"""Add Responsibilities and Achievements

Revision ID: 722b8f7c59aa
Revises: 7e0c2e41aa18
Create Date: 2025-10-06 14:31:33.352683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722b8f7c59aa'
down_revision = '7e0c2e41aa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('responsibilities', sa.JSON(), nullable=True))
    op.add_column('experience', sa.Column('achievements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'achievements')
    op.drop_column('experience', 'responsibilities')
    # ### end Alembic commands ###
