"""Removed Responsibilities and Achievements

Revision ID: 7e0c2e41aa18
Revises: 3ebc9e579235
Create Date: 2025-10-06 12:21:42.530036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0c2e41aa18'
down_revision = '3ebc9e579235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibility')
    op.drop_table('achievement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('experience_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], name='achievement_experience_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='achievement_pkey')
    )
    op.create_table('responsibility',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('experience_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], name='responsibility_experience_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='responsibility_pkey')
    )
    # ### end Alembic commands ###
