"""add is_correct to answers

Revision ID: 88a5f21566c5
Revises: 4320443fdd6e
Create Date: 2025-12-17 15:47:07.472679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a5f21566c5'
down_revision = '4320443fdd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
