"""Hopefully removed to Responsibility and Achievement

Revision ID: 8ddd7f864340
Revises: 722b8f7c59aa
Create Date: 2025-10-15 15:17:17.549127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ddd7f864340'
down_revision = '722b8f7c59aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'achievements')
    op.drop_column('experience', 'responsibilities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('responsibilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('achievements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
