"""Add detailed job requirements

Revision ID: 98a56a91cea9
Revises: accc2d21f09f
Create Date: 2025-09-04 10:48:40.773986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a56a91cea9'
down_revision = 'accc2d21f09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    degree_enum = sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORAL', name='degree_enum')
    degree_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('degree', 'degree',
                    existing_type=sa.VARCHAR(length=150),
                    type_=degree_enum,
                    existing_nullable=False,
                    postgresql_using='degree::text::degree_enum')
    op.add_column('job_required_certificate',
                  sa.Column('title_match_type', sa.String(length=20), nullable=False, server_default='including'))
    op.add_column('job_required_certificate',
                  sa.Column('issuer_match_type', sa.String(length=20), nullable=False, server_default='including'))
    op.add_column('job_required_experience',
                  sa.Column('role_title_match_type', sa.String(length=20), nullable=False, server_default='including'))
    op.add_column('job_required_experience', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('job_required_experience',
                  sa.Column('country_match_type', sa.String(length=20), nullable=False, server_default='including'))
    op.add_column('job_required_skill',
                  sa.Column('title_match_type', sa.String(length=20), nullable=False, server_default='including'))

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_required_skill', 'title_match_type')
    op.drop_column('job_required_experience', 'country_match_type')
    op.drop_column('job_required_experience', 'country')
    op.drop_column('job_required_experience', 'role_title_match_type')
    op.drop_column('job_required_certificate', 'issuer_match_type')
    op.drop_column('job_required_certificate', 'title_match_type')
    op.alter_column('degree', 'degree',
                    existing_type=sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORAL',
                                          name='degree_enum'),
                    type_=sa.VARCHAR(length=150),
                    existing_nullable=False)
    op.execute('DROP TYPE degree_enum;')
# ### end Alembic commands ###
