"""Add is_public column to profile databases.

Revision ID: accc2d21f09f
Revises: 2cdc425afe13
Create Date: 2025-08-20 13:00:24.099992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accc2d21f09f'
down_revision = '2cdc425afe13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('degree', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('experience', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('skill', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'is_public')
    op.drop_column('experience', 'is_public')
    op.drop_column('degree', 'is_public')
    op.drop_column('certificate', 'is_public')
    # ### end Alembic commands ###
