"""Add cover letter to the database

Revision ID: b7ce7321b735
Revises: 98a56a91cea9
Create Date: 2025-09-04 19:52:43.618626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ce7321b735'
down_revision = '98a56a91cea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_application', 'cover_letter')
    # ### end Alembic commands ###
