"""Add question_count to tests table

Revision ID: fd5d3c9ddc0e
Revises: 3ace561c4ca0
Create Date: 2025-12-08 11:25:39.470366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5d3c9ddc0e'
down_revision = '3ace561c4ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('question_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'question_count')
    # ### end Alembic commands ###
